# Generated by Django 5.2 on 2025-05-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pin_images/'),
        ),
    ]
