# Generated by Django 5.2 on 2025-05-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappin',
            name='category',
            field=models.CharField(choices=[('user', 'User Pin'), ('coffee', 'Coffee Shop'), ('drugstore', 'Drugstore')], default='user', max_length=20),
        ),
    ]
