# Generated by Django 5.2 on 2025-05-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0004_mappin_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappin',
            name='category',
            field=models.CharField(choices=[('user', 'User Pin'), ('dispensary', 'Cannabis Dispensary')], default='user', max_length=20),
        ),
    ]
