# Generated by Django 5.2 on 2025-05-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0005_alter_mappin_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappin',
            name='category',
            field=models.CharField(choices=[('smoke', 'Smoke Location'), ('dispensary', 'Dispensary')], default='smoke', max_length=20),
        ),
    ]
