# Generated by Django 5.2 on 2025-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappin',
            name='category',
            field=models.CharField(choices=[('smoke', 'Smoke Spot'), ('dispensary', 'Dispensary')], default='smoke', max_length=20),
        ),
        migrations.AlterField(
            model_name='mappin',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
    ]
