# Generated by Django 5.2 on 2025-05-13 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0011_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
